project:
  type: website
  output-dir: _site

publish:
  method: gh-pages
  branch: gh-pages

website:
  title: "ADeclercq"

format:
  html:
    css: styles.css
    theme: none
    page-layout: full


resources:
  - images
  - icons
  