project:
  type: website

publish:
  method: gh-pages
  branch: gh-pages

website:
  title: "ADeclercq"
  site-url: "https://arthurdeclercq.bio"

format:
  html:
    theme: none
    css: styles.css
    page-layout: full


resources:
  - images
  - icons